set MIDDLEWARE_HTTP_PORT=8080
set MIDDLEWARE_DEBUG_PORT=5005
set MIDDLEWARE_SSH_PORT=3020
set MIDDLEWARE_FTP_PORT=2020
set MIDDLEWARE_FTP_PASSIVE_INITIAL_PORT=61000
set MIDDLEWARE_FTP_PASSIVE_FINAL_PORT=61050
set MIDDLEWARE_FRONTEND_ACTIVE=true
set MIDDLEWARE_FRONTEND_PORT=3000
set MIDDLEWARE_SHARED_DIR_PATH=%cd%\volumes\shared
set MIDDLEWARE_DATA_DIR_PATH=%cd%\volumes\data_dir
set MIDDLEWARE_LOG_DIR_PATH=%cd%\volumes\log_dir
set TIMEZONE=Europe/Rome
set RESTSTUB_HTTP_PORT=8081
set RESTSTUB_DEBUG_PORT=5006
for /f "delims=[] tokens=2" %%a in ('ping -4 -n 1 %ComputerName% ^| findstr [') do set DOCKER_HOST_IP=%%a
set CONFIGURATION_TYPE=LOCAL_TO_LOCAL
set MAPPINGS_TYPE=LOCAL
