#!/bin/bash

export MIDDLEWARE_HTTP_PORT=8080
export MIDDLEWARE_DEBUG_PORT=5005
export MIDDLEWARE_SSH_PORT=3020
export MIDDLEWARE_FTP_PORT=2020
export MIDDLEWARE_FTP_PASSIVE_INITIAL_PORT=61000
export MIDDLEWARE_FTP_PASSIVE_FINAL_PORT=61050
export MIDDLEWARE_FRONTEND_ACTIVE=true
export MIDDLEWARE_FRONTEND_PORT=3000
export MIDDLEWARE_SHARED_DIR_PATH=$(pwd)/volumes/shared
export MIDDLEWARE_DATA_DIR_PATH=$(pwd)/volumes/data_dir
export MIDDLEWARE_LOG_DIR_PATH=$(pwd)/volumes/log_dir
export TIMEZONE=Europe/Rome
export RESTSTUB_HTTP_PORT=8081
export RESTSTUB_DEBUG_PORT=5006
export DOCKER_HOST_IP=$(ifconfig | awk '/inet /&&!/127.0.0.1/{print $2;exit}')
export CONFIGURATION_TYPE=LOCAL_TO_LOCAL
export MAPPINGS_TYPE=LOCAL
